### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by RealXiaoLin** [RealXiaoLin/protospace-31987#2]
# ProtoSpaceのURL
https://github.com/RealXiaoLin/protospace-31987

# 本番環境のURL
https://protospace-31987.herokuapp.com

**Comment by RealXiaoLin** [comment]
> ##ProtoSpaceのURL
> https://github.com/RealXiaoLin/protospace-31987
> 
> ##本番環境のURL
> https://protospace-31987.herokuapp.com

**Comment by hiraoka1102** [comment]
小林さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・誤った情報では、そのページに留まる
→新規登録時の「パスワード再入力」欄が空欄でも登録できてしまいました！

・必要な情報を入力すると、プロトタイプが編集でき、詳細ページへ遷移する
→プロトタイプタイトルを変更してみたところ、変更前のタイトルのままでございました！

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by RealXiaoLin** [comment]
> 小林さん、ご提出ありがとうございます！
> 挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
> 
> [修正箇所]
> ・誤った情報では、そのページに留まる
> →新規登録時の「パスワード再入力」欄が空欄でも登録できてしまいました！
> 
> ・必要な情報を入力すると、プロトタイプが編集でき、詳細ページへ遷移する
> →プロトタイプタイトルを変更してみたところ、変更前のタイトルのままでございました！
> 
> 修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
> ※新しいissueを作っていただく必要はありません
> https://forms.gle/ZdLeprTTWhMA8aZA7

修正が完了いたしましたので、フォームを提出させていただきました。
ご確認をお願いいたします。

**Comment by hiraoka1102** [comment]
小林さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
